language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
    secure: mRolLOeUQ15S2FCGOHv8GEelf0gTUZIHmSb83zx8v0Hcc9jL8XJse+RkwJ6p2epwxSfSgORtQGZC27RUNeP4i+bOwlNb29SW6YhSG83yObDST1+xngFAaa2BCobKQLZhLW561YlvOXCUnHQMa90KaOc7e+Nkv4e/5YvdqwSAvCmY+bnJrAI3BRQOvEQLue0nbcJoTSIs31HbECOIJypWxLXz/Iv8xo6FOsMN4eXSsUWgsmSlD+NNsYi5aKh1Gu5jMUO6ZzA20aqX30nurfRASX5wxQjEQjmvZnyrcnWM+jv5gNjmqTLildTtmcqtH7Ejal/mxprEJX9jYSgSkX/rwx2WcEXUwkWqE3W8Ym3qYZt67ZotrGvvuHINh/qhRDgphkuUS7JvnEdfNIfrgEGkPljFreajUr6f9q4S/3R7s1ED2BUovNLGTyATIUwXfqPVk/suRsR1pOBDEWf6fngW0wu5fH3ZVndhw6NtsM3ortlp9f0hmgeWVmKje3R6mlJJ3LOuLRSXpJpK9+Ostg0BDgLThIKSni4H4n6nEfS7BldjxZyI+U28aacPgaCOhquGfRwESdRiDstJLB9cqGvnYdpklJ3nDZtHu3WjU6Ih4EQempDieHqnhBbOoTKuY/x5kbdZznMTvOeud0IxfqZUyN/M1K3kLhBvSJ73budMgNw=
install:
- pip install -r requirements.txt
script:
- python manage.py tests
deploy:
  api_key:
  - secure: 41oSylSzuIETkcOiju0Sj/dpfBDthg30TbzimK/BOvnN1HCi/q+VlMKjf1EgNBpNAhoyd7GpI+uTjBw/S0D5drN8T0H7z+FPCmdH9Y7lplnin4LT8RVsZKBnzdP9B+fKqwu2dLPOvOEmvr36HRLm2FztPzZDN3fFkGEANM/qhRC9Rz/1e0Uiqlpf2qoGdzyFs6379cmgBNQ06erkUxxHr+xIfOKd89B7zuK9dk7z7UshT9pZapoaL/Ce1Nvt5VeSpDfUx3swwtu4VXYU4SZrsfwevfzOD/tu//dIkzJmAGwLxNXehovr9kVkcc1nPaN+178X7nYRkIxnuc9wijFaMXQmRyOX1mkCdp97C0QFenZT97SvN0EH5Zxwtn/R4LKqfomKyCYaYWxYlQRa9ltShfKfw8j7Lf6eh14mkPee+XWBxAh2XAOsIjvM5gbnbdSNY/c8+yulkVXhJBlP9ACPmxwnoROVBc3EHW2vlx2h5/JXqE8JAd9XNXpvt6CE9atm3V2HPfY+TPant5qFK/8qDHmCH4PU8vj4GxamRceg6Eg680egO46Vvo4RMrzbI/yXHU8Yy2TjcPKM6d4dvp7GEaf5d/anML+eBjeeFbJ7P042XV9939TsdaQKt5VK+sDuFqVXHAOA6SF0v1YVidPEfLG51udwxDC1lGheGvF9e/Q=
