language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
    secure: Gc1eD8iGpax5JFtMPxi6cWbm+Whe7KAdxTKE/btDUJo8e/H8UzDQwRzo5YWaS4X6RrlLfrSij0tlO4Qq4fFDl1rhMLwdw33aeEnbYqg/gA7owmXfk1UfG5+WfkEG5y0eB0ze+ghDkdiugC/hIQXpMLpmpHutOUuNEKoXZToEQJ90Bky0TOv6QoVFawsf8Kg3bcEaeVGWcv1ynWmVUGPLgBDm5vMFGmXt0fVw0bJp8hvjIiFg8KTENfOY2rvtLz1SwqdXxfEbCm5J/OZsIX4dR8PTVyQfwMO2QPnLq5pwRRxwgOx1usJQVyxhMy7hykNBQXW2FbpUOqT9/Oa/fAhmHNSWm7KEN7yJR1HCc8cHu6yJbNK26XMc1HZT3w3CE9z34TeFd0UAHHzfdNW0nM5Zr7ChBV5qxKHSZ2qXbF6HdT41zU1+/UnqA010Jnltonum6/9cfCS9UiKdkSbX2eq2Fa5EYO1qEuKm9J2DsC7Asj0p7KwIXX1oEVjEDyjl4JTsZhol1v+zRLHZMFQu8rleR43OLWEfDRG6y9UGiOJh9IRL2RlPKhm3g7RFki+0965VANdpV4IdS1LYU30iJjmFQEc8O0kS0LHEKZYSaJkPZzRC8jxbedy5V87gZxo2d0NP4flmRgGE1507zc9x9z29o8d1b3b+P4CVFNQlpLOQvho=
install:
- pip install -r requirements.txt
script:
- python manage.py tests
deploy:
  api_key:
    secure: 41oSylSzuIETkcOiju0Sj/dpfBDthg30TbzimK/BOvnN1HCi/q+VlMKjf1EgNBpNAhoyd7GpI+uTjBw/S0D5drN8T0H7z+FPCmdH9Y7lplnin4LT8RVsZKBnzdP9B+fKqwu2dLPOvOEmvr36HRLm2FztPzZDN3fFkGEANM/qhRC9Rz/1e0Uiqlpf2qoGdzyFs6379cmgBNQ06erkUxxHr+xIfOKd89B7zuK9dk7z7UshT9pZapoaL/Ce1Nvt5VeSpDfUx3swwtu4VXYU4SZrsfwevfzOD/tu//dIkzJmAGwLxNXehovr9kVkcc1nPaN+178X7nYRkIxnuc9wijFaMXQmRyOX1mkCdp97C0QFenZT97SvN0EH5Zxwtn/R4LKqfomKyCYaYWxYlQRa9ltShfKfw8j7Lf6eh14mkPee+XWBxAh2XAOsIjvM5gbnbdSNY/c8+yulkVXhJBlP9ACPmxwnoROVBc3EHW2vlx2h5/JXqE8JAd9XNXpvt6CE9atm3V2HPfY+TPant5qFK/8qDHmCH4PU8vj4GxamRceg6Eg680egO46Vvo4RMrzbI/yXHU8Yy2TjcPKM6d4dvp7GEaf5d/anML+eBjeeFbJ7P042XV9939TsdaQKt5VK+sDuFqVXHAOA6SF0v1YVidPEfLG51udwxDC1lGheGvF9e/Q=
